### ISSUE TITLE
Use SHA instead of PR head reference

### ISSUE THREAD

**Issue by KevinGrandon** [mvines/ci-gate#41]
We're seeing a bunch of CI failures after switching to CI-Gate with the following error:

> error: cannot lock ref 'refs/remotes/origin/pull/XXX/head': unable to resolve reference 'refs/remotes/origin/pull/XXX/head'

The only difference in the build log appears that we're no longer using the commit sha, and are instead using the PR head reference. 

Happy to try to work on this, just want to see if this would be an acceptable change to merge upstream.

**Comment by mvines** [comment]
I spent a bunch of time digging into the buildkite source, the best work around I could come up with is documented at https://github.com/mvines/ci-gate#buildkite-configuration

I don't think using the commit sha will work, as when buildkite pulls the git project it won't pull the PR branches so the commit sha won't exist in the local clone (without that `BUILDKITE_REFSPEC` override)

**Comment by KevinGrandon** [comment]
Thanks for the context, that's super helpful :)  

> I spent a bunch of time digging into the buildkite source, the best work around I could come up with is documented at https://github.com/mvines/ci-gate#buildkite-configuration

I thought we uploaded a custom environment hook, but maybe we missed something. Will look at this again.

**Comment by KevinGrandon** [comment]
So it seems like this is not an issue with the environment hook, we have that running ok. Currently debating if we want to run a fork of the agent temporarily /w a fix in place. Maybe @lox knows a workaround, or could say if they would accept a PR which could allow us to fall into the `b.PullRequest = true` path.

**Comment by lox** [comment]
Sounds like it might be related to https://github.com/buildkite/agent/issues/782?

We have a PR internally that allows `BUILDKITE_PULL_REQUEST` and `BUILDKITE_PULL_REQUEST_BASE_BRANCH` to be set via the API to get that behaviour, would that fix the problem?

Otherwise, we are totally open to suggestions on agent changes to solve the problem.

**Comment by KevinGrandon** [comment]
> We have a PR internally that allows BUILDKITE_PULL_REQUEST and BUILDKITE_PULL_REQUEST_BASE_BRANCH to be set via the API to get that behaviour, would that fix the problem?

I think that sounds like a pretty nice add to me that might solve this as well. Any thoughts @mvines ?

**Comment by lox** [comment]
We've just merged a PR that adds the following properties to the build api:

* pull_request_id
* pull_request_base_branch
* pull_request_repository

If added to https://github.com/mvines/ci-gate/blob/4b545cfa6d68a20f0b075099e86e6812f73c350c/index.js#L121-L128 with the correct bits from github webhooks, your build will get the correct refspec.

**Comment by KevinGrandon** [comment]
I think we had issues when passing along the PR details in build API, but I'm also not sure if we've had the race condition recently. I've been away from our open source stuff, but I'll try to do some more investigation soon.

Will reopen this or file a new issue if we're able to reproduce it.
